#  2007/10/12 20:19:22
# R script alpha-investing

source("/Users/bob/work/papers/fdr/alpha_investing.R")

# ---------------------------------------------
# Basic simple test
# ---------------------------------------------

p <- c(0.06, 0.0001, 0.01, 0.10, 0.10)

alpha.rule <- function(w,...) { w/2 }

test <- make.test.procedure(length(p), alpha.rule); 

for (j in 1:length(p)) { test$test(j,p[j]) }
test$print();

# ---------------------------------------------
# Bonferroni test procedure
# ---------------------------------------------

p <- c(0.06, 0.0001, 0.01, 0.10, 0.10)

test <- make.bonferroni.test.procedure(length(p));

for (j in 1:length(p)) { test$test(j,p[j]) }
test$print();


# ---------------------------------------------
# Conservative test procedure
# ---------------------------------------------

p <- c(0.004, 0.01, 0.01, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10)

test <- make.conservative.test.procedure(length(p));

for (j in 1:length(p)) { test$test(j,p[j]); test$print(); }
test$print();

test <- conservative.sequential.test(p)



# ---------------------------------------------
# Aggressive test procedure
# ---------------------------------------------

p <- c(0.004, 0.01, 0.01, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10)

p <- generate.pvalues(200,100)

test <- make.aggressive.test.procedure(length(p), regulator=recip.regulator);

test$print();
for (j in 1:length(p)) { 
	test$test(j,p[j]); test$print(); 
}


# ---------------------------------------------
# Simes-like BH, wBH test procedures
# ---------------------------------------------

m <- 200
p <- generate.pvalues(m, pi=0.03)
m1 <- .number.false.nulls  # global generated by prior call to gen p-values
which(v1 <- simes.sequential.test(p))
which(v2 <- bh.test(p))
which(v2 <- bh.test(p))
which(v3 <- sim.wbh.test(p))
which(v4 <- wbh.test(p, rep(c(TRUE,FALSE), c(m1,m-m1))))

color <- rep("black",m); color[45]<-"red"
plot(1:m, p, col=color)

tests <- list(bh.test, sim.wbh.test, simes.sequential.test);
m <-   200
N <-  1000
v <- matrix(nrow=N, ncol=length(tests));
r <- matrix(nrow=N, ncol=length(tests));

simulate.tests(tests, m, 0.02)

sd(r[,2]-r[,1])
table(r[,1],r[,2])
table(v[,1],v[,2])


# ---------------------------------------------
# Streaming test
# ---------------------------------------------

p <- c(0.06, 0.0001, 0.01, 0.10, 0.10)

alpha.rule <- function(w,...) { w/2 }

test <- make.test.procedure(0, alpha.rule); 

for (j in 0:99) { test$test(j,p[1+j%%(length(p))]) }
test$print();

# testing simulation code
p01 <- .05; odds <- 4; mu1 <- 3;
max.n.tests <- 100; n.trials <- 1
v <- s <- r <- rep(0,max.n.tests)

c(num.first, num.last, found.first, found.last)

# ---------------------------------------------
# Streaming tests (run on another box)
#    Produces fig_streama, fig_streamb  (Appears as figure 3)
# ---------------------------------------------
source("alpha_investing.R")

simres <- vector("list", 0)

p01 <- c(.05,.025,.01,.005,.0025)
n.trials <- 10;

odds <- 9;
run.experiment(p01, odds, n.trials);
save(simres, file="simres");

odds <- 4;
run.experiment(p01, odds, n.trials);
save(simres, file="simres");


load("/Users/bob/work/papers/fdr/simres_4");
temp <- simres;
load("/Users/bob/work/papers/fdr/simres_9");
simres <- c(simres,temp)

cols <- matrix(unlist(simres), ncol=11,byrow=TRUE)
colnames(cols) <- c("p01","odds","trials","n","w","fdr","pow","fp","lp","fn","ln")
cols[,c(1,5:9)]

# Check of average power ...
nc  <- 10000          # number of clusters, each of geometric length
fp <- .2; lp <- .60   # first power, higher power after the first
p   <- .1
len <- 1+rgeom(nc,p)
len1<- length(which(len==1))
fst <- rbinom(1,nc,fp)
rst <- rbinom(1,sum(len)-nc,lp)
cat(" Average power is ", (fst+rst)/sum(len))
#  this one ought to be lp - p(lp-fp)
cat(" Avg last power   ", (rbinom(1,len1,fp)+rbinom(1,nc-len1,lp))/nc)


sym <- c(rep(1,5),rep(4,5))
p10 <- extract(simres, "p01")*extract(simres,"odds")

postscript("figure3b.ps")
pow <- extract(simres, "power")
plot(1/p10[1:5],pow[1:5], pch=1, type="b",xlim=c(2,100), ylim=c(0.1,0.8),
	xlab="Mean Cluster Size", ylab="Power", log="x")
points(1/p10[6:10],pow[6:10],type="b", pch=4)
text(6,0.15,"k=9")
text(4,0.50,"k=4")
dev.off()

postscript("figure3a.ps")
plot(1/p10, extract(simres, "fdr"),  pch=sym, xlim=c(2,100), ylim=c(0.0375,0.051),
	xlab="Mean Cluster Size", ylab="FDR", log="x")
abline(h=0.05, lty=3);
dev.off()
# cols <- matrix(unlist(simres), ncol=11, byrow=TRUE)
# points(rep(1/p10,2),c(cols[,10],cols[,11]),pch=rep(sym,2),log="x",col=rep(col,2))


# plot sequential results for a trial
test$print(); 
n <- test$state()$current.index;  R <- S + V
plot(1:n, cumsum(V[1:n])/cumsum(R[1:n]))
cat(" Totals:  V ", sum(V), "    S ", sum(S), "   R ", sum(R), "\n");
cat("  Power:  ", sum(S), "/", sum(State)," = ",sum(S)/sum(State),"\n");

# ---------------------------------------------
# Simulation of FDR, mFDR (Figure 1: similarity of fdr, mfdr)
# fig1.pdf, 380 x 350
# Have to kludge the wbh by feeding bh the weighted p-values
# ---------------------------------------------

tests <- list(  bh.test, sim.wbh.test, naive.test, bonferroni.test );
test.names <- c("bh", "wbh", "naive", "bon");

pi <- c(0, 0.005, 0.01, 0.02,0.04,0.08,0.16,0.32,0.64,0.975)

m <-   200
N <- 10000
v <- matrix(nrow=N, ncol=length(tests));
r <- matrix(nrow=N, ncol=length(tests));

fdr  <- matrix(nrow=length(pi), ncol=length(tests))
mfdr <- matrix(nrow=length(pi), ncol=length(tests))
for (j in 1:length(pi)) {
	simulate.tests(tests, m, pi[j])
	fdr [j,] <- apply(v/pmax(r,1),2,mean)
	mfdr[j,] <- apply(v,2,mean)/(0.95 + apply(r,2,mean))
}
dimnames(v) <- dimnames(r) <- list(NULL, test.names)
dimnames(fdr) <- dimnames(mfdr)  <- list(NULL, test.names)


# Draw the plot

offset <- 0.001;
x <- function(xx) { log(offset + xx) }
y <- function(yy) { log(offset + yy) }

postscript("figure1.ps")
par(mar=c(5,4,1,2)+.1) # bottom left top right
plot (x(pi), y(fdr[,"bh"]), type="b", col=1, pch=20, ylim=y(c(0,1)),
      axes=FALSE, ylab = "Criterion", 
      xlab=expression(paste("Proportion False (",pi[1],")")));
xax <- c(0, 0.005, 0.02, 0.08,0.32, 1)
axis(1, at = x(xax), labels = formatC(xax, format="fg"))
yax <- c(0,0.01, 0.05, 0.20, 0.5, 1)
axis(2, at=y(yax), labels=formatC(yax, format="fg"))

abline(a=y(0.05), b=0, lty=3);
lines(x(pi), y(fdr[,2]), type="b", col=1, pch="*")  # 2
lines(x(pi), y(fdr[,3]), type="b", col=1, pch="+")  # 3
lines(x(pi), y(fdr[,4]), type="b", col=1, pch=21)   # 4

lines(x(pi), y(mfdr[,1]), type="l", col=1, lty=2)
# lines(x(pi), y(mfdr[,2]), type="l", col=1, lty=2)
lines(x(pi), y(mfdr[,3]), type="l", col=1, lty=2)
lines(x(pi), y(mfdr[,4]), type="l", col=1, lty=2)
par(mar=c(5,4,4,2)+.1)
dev.off()

write.table(cbind(pi,fdr,mfdr), file="/Users/bob/work/papers/fdr/fig1.tab",
             row.names=formatC(pi))


file.data <- read.table(file="/Users/bob/work/papers/fdr/fig1.tab");
test.names <- c("bh", "wbh", "naive", "bon");
pi   <- file.data[,1];
fdr  <- file.data[,2:5];
mfdr <- file.data[,6:9];



# ------------------------------------------------------------
# Simulation of FDR, mFDR (Figure 2: FDR of different methods)
# ------------------------------------------------------------

tests <- list( sim.wbh.test, bh.test, simes.sequential.test, 
				aggressive.sequential.test, shuffled.aggressive.sequential.test );
test.names <- c("wbh", "bh", "Simes", "aggr", "shuffle");

pi <- c(0, 0.005, 0.01, 0.02, 0.04,0.08,0.16,0.32,0.64,0.975)

m <-   200
N <- 10000
v <- matrix(nrow=N, ncol=length(tests));
r <- matrix(nrow=N, ncol=length(tests));

fdr  <- matrix(nrow=length(pi), ncol=length(tests))
mfdr <- matrix(nrow=length(pi), ncol=length(tests))
pow  <- matrix(nrow=length(pi), ncol=length(tests))
for (j in 1:length(pi)) {
	simulate.tests(tests, m, pi[j])
	fdr [j,] <- apply(v/pmax(r,1),2,mean)
	mfdr[j,] <- apply(v,2,mean)/(0.95 + apply(r,2,mean))
	pow [j,] <- apply(r-v,2,mean)  # only correct rejections

}

# fdr[1,3:4] <- mean(fdr[1,3:4]) # equiv under complete null
dimnames(v) <- dimnames(r) <- list(NULL, test.names)
dimnames(fdr) <- dimnames(mfdr) <- dimnames(pow) <- list(NULL, test.names)

# Draw the plot 
offset <- 0.001;
x <- function(xx) { log(offset + xx) }
y <- function(yy) {  yy }

postscript("figure2a.ps")
par(mar=c(5,4,1,2)+.1) # bottom left top right   380 x 350
plot (x(pi), fdr[,"bh"], type="b", col="black", pch=20, ylim=c(0,0.055), 
      ylab = "FDR", xlab=expression(paste("Proportion False (",pi[1],")")),
      axes=FALSE);  abline(a=0.05, b=0, lty=3);
xax <- c(0, 0.005, 0.02, 0.08, 0.32, 1)
axis(1, at = x(xax), labels = formatC(xax, format="fg"))
yax <- c(0, 0.01, 0.02, 0.03, 0.04,  0.05, 0.06)
axis(2, at=y(yax), labels=formatC(yax, format="fg"))

lines(x(pi), y(fdr[,"wbh"]    ), type="b", col="black", pch="*")  # dont bother to show mfdr
lines(x(pi), y(fdr[,"Simes"]  ), type="b", col="black", pch=21)
lines(x(pi), y(fdr[,"aggr"]   ), type="b", col="black", pch=25)
lines(x(pi), y(fdr[,"shuffle"]), type="b", col="black", pch=24)
par(mar=c(5,4,4,2)+.1)
dev.off()

write.table(cbind(pi,fdr,mfdr,pow), file="/Users/bob/work/papers/fdr/fig2.tab",
             row.names=formatC(pi))

file.data <- read.table(file="/Users/bob/work/papers/fdr/fig2.tab");
test.names <- c("wbh", "bh", "Simes", "aggr", "shuffle");
pi   <- file.data[,1];		
fdr  <- file.data[,2:6];	colnames(fdr)  <- test.names;
mfdr <- file.data[,7:11];	colnames(mfdr) <- test.names;
pow  <- file.data[,12:16];	colnames(pow)  <- test.names;


# -------------------------------------------------------------------------
# Plot the number rejected for power relative to bh (Figure 3, fig3.pdf)
# Uses same data as in fig2 and appears as second frame of Fig 2 in paper.
# -------------------------------------------------------------------------

pow[1,3:4] <- mean(pow[1,3:4]) # aggressive and shuffled are same

offset <- 0.001;
x <- function(xx) { log(offset + xx) } # this function transforms the x axis

postscript("figure2b.ps")
par(mar=c(5,4,1,2)+.1) # bottom left top right   380 x 350
plot(x(pi),pow[,"wbh"]/pow[,"bh"], type="b", col="black", pch="*",axes=FALSE,
          ylim=c(0.4,2.1), xlim=c(-5.2,.1), ylab="Power Relative to BH", 
          xlab=expression(paste("Proportion False (",pi[1],")")))
xax <- c(0.005, 0.02, 0.08, 0.32, 1)
axis(1, at = x(xax), labels = formatC(xax, format="fg"))
yax <- seq(0.5,2.0,0.5);
axis(2, at=yax, labels=formatC(yax, format="fg"))
lines(x(pi), rep(1,length(pi)), type="b", col="black", pch=20) # BH
lines(x(pi),pow[,"Simes"]  /pow[,"bh"], type="b", col="black", pch=21)
lines(x(pi),pow[,"aggr"]   /pow[,"bh"], type="b", col="black", pch=25)
lines(x(pi),pow[,"shuffle"]/pow[,"bh"], type="b", col="black", pch=24)
par(mar=c(5,4,4,2)+.1)
dev.off()


